### ISSUE TITLE
.toString() bugs

### ISSUE THREAD

**Issue by lambdaupb** [anthonynsimon/jurl#2]
The string serialization seems incorrect. Maybe not all URL segments are properly urlencoded ?

Also UTF-8 is assumed in urlencoded parts, but in my corpus from the web there are some examples of latin1 encoded ones. I'n not sure about what the standard says, but chrome recognizes it.

```
import com.anthonynsimon.url.URL;

public class JurlTest {
  public static void main(String[] args) {
    test("http://abc.net/1160x%3E/quality/");
    test("http://db-engines.com/en/system/PostgreSQL%3BRocksDB");
    test("http://xzy.org/test/hei%DFfl"); // latin1
    test("http://www.net/decom/category/AA/A_%26_BBB/AAA_%26_BBB/"); // !!!
    test("https://en.wikipedia.org/wiki/Eat_one%27s_own_dog_food");
  }

  private static void test(String url) {
    try {
      Thread.sleep(10);
    } catch (InterruptedException e) {
    }
    try {
      URL parse = URL.parse(url);

      if(!parse.toString().equals(url)) {
        System.out.print("NOT EQUAL: ");
        System.out.println(url);
        System.out.println(parse.toString());
        System.out.println();
      }

    } catch (Exception e) {
      System.out.print("KAPUTT: ");
      System.out.println(url);
      e.printStackTrace();
      System.out.println();
    }
  }
}

```

results in 
```
NOT EQUAL: http://abc.net/1160x%3E/quality/
http://abc.net/1160x>/quality/

NOT EQUAL: http://db-engines.com/en/system/PostgreSQL%3BRocksDB
http://db-engines.com/en/system/PostgreSQL;RocksDB

java.lang.StringIndexOutOfBoundsException: String index out of range: 15
	at java.lang.String.substring(String.java:1963)
	at com.anthonynsimon.url.PercentEncoder.decode(PercentEncoder.java:181)
	at com.anthonynsimon.url.DefaultURLParser.parse(DefaultURLParser.java:85)
	at com.anthonynsimon.url.URL.parse(URL.java:73)
	at JurlTest.test(JurlTest.java:20)
	at JurlTest.main(JurlTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
KAPUTT: http://xzy.org/test/hei%DFfl

NOT EQUAL: http://www.net/decom/category/AA/A_%26_BBB/AAA_%26_BBB/
http://www.net/decom/category/AA/A_&_BBB/AAA_&_BBB/

NOT EQUAL: https://en.wikipedia.org/wiki/Eat_one%27s_own_dog_food
https://en.wikipedia.org/wiki/Eat_one's_own_dog_food
```

**Comment by lambdaupb** [comment]
maybe this line should return true:
https://github.com/anthonynsimon/jurl/blob/master/src/main/java/com/anthonynsimon/url/PercentEncoder.java#L54

**Comment by anthonynsimon** [comment]
I'll take a look into it. Thanks for reporting it.
